version: "3.8"

services:
  db:
    image: postgres
    container_name: student-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: studentdb
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: student-api
    ports:
      - "8080:8080"
    depends_on:
      - db
